openapi: 3.0.3
info:
  title: API для визуализации генеалогического исследования
  version: "1.0.1"
tags:
  - name: GenealogyVisualize
    description: API для визуализации генеалогического исследования
paths:
  /genealogy-visualizer/graph:
    post:
      tags:
        - GenealogyVisualize
      operationId: getGenealogyVisualizeGraph
      summary: "Запрос данных для визуализации генеологического исследования"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./model/genealogy/visualizer/genealogy-visualize-rq.yaml"
        required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenealogyVisualizeResponse"
        404:
          description: "Failed to find data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenealogyVisualizeErrorResponse"

components:
  schemas:
    GenealogyVisualizeResponse:
      type: object
      oneOf:
        - $ref: "./model/genealogy/visualizer/genealogy-visualize-graph.yaml"
        - $ref: "#/components/schemas/GenealogyVisualizeErrorResponse"
    GenealogyVisualizeErrorResponse:
      $ref: "./model/common/error.yaml"
