openapi: 3.0.3
info:
  title: API для визуализации генеалогического исследования
  version: "1.0.0"
tags:
  - name: GenealogyVisualize
    description: API для визуализации генеалогического исследования
paths:
  /genealogy-visualizer/graph:
    get:
      tags:
        - GenealogyVisualize
      operationId: getGenealogyVisualizeGraph
      summary: "Запрос данных для визуализации генеологического исследования"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenealogyVisualizeRq"
        required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenealogyVisualizeGraph"
        400:
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: "Data not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    GenealogyVisualizeGraph:
      $ref: "./model/genealogy/visualizer/genealogy-visualize-graph.yaml"
    GenealogyVisualizeRq:
      $ref: "./model/genealogy/visualizer/genealogy-visualize-rq.yaml"
    ErrorResponse:
      $ref: "./model/common/error-response.yaml"
