const getGraphResponse = [
    {
        id: 1,
        fullName: { name: 'Rébecca', surname: 'Cowitz', lastName: 'Bampton' },
        birthDate: '4/12/1910',
        deathDate: '10/22/1931',
        sex: 'Female',
        group: 'Teal',
    },
    {
        id: 2,
        fullName: { name: 'Maëlle', surname: 'Pickston', lastName: 'Renowden' },
        birthDate: '5/29/1914',
        deathDate: '11/16/1933',
        sex: 'Female',
        group: 'Teal',
    },
    {
        id: 3,
        fullName: { name: 'Åsa', surname: 'McNysche', lastName: 'Livingston' },
        birthDate: '10/30/1968',
        deathDate: '11/7/1978',
        sex: 'Female',
        group: 'Yellow',
    },
    {
        id: 4,
        fullName: { name: 'Yóu', surname: 'Band', lastName: 'Loughhead' },
        birthDate: '4/22/1915',
        deathDate: '7/9/1935',
        sex: 'Female',
        group: 'Turquoise',
    },
    {
        id: 5,
        fullName: { name: 'Andréa', surname: 'Fosdyke', lastName: 'Kobierra' },
        birthDate: '2/16/1921',
        deathDate: '11/28/1921',
        sex: 'Genderqueer',
        group: 'Green',
    },
    {
        id: 6,
        fullName: { name: 'Océane', surname: 'Hartell', lastName: 'Egleton' },
        birthDate: '3/7/1956',
        deathDate: '1/6/1988',
        sex: 'Male',
        group: 'Crimson',
    },
    {
        id: 7,
        fullName: { name: 'Nélie', surname: 'Goscar', lastName: 'Bendtsen' },
        birthDate: '11/11/1939',
        deathDate: '8/9/1985',
        sex: 'Female',
        group: 'Turquoise',
    },
    {
        id: 8,
        fullName: { name: 'Réjane', surname: 'Spray', lastName: 'Matthesius' },
        birthDate: '12/2/1930',
        deathDate: '3/15/1920',
        sex: 'Female',
        group: 'Violet',
    },
    {
        id: 9,
        fullName: {
            name: 'Célestine',
            surname: 'Mulhill',
            lastName: 'Coppock.',
        },
        birthDate: '10/7/1920',
        deathDate: '10/9/1958',
        sex: 'Polygender',
        group: 'Red',
    },
    {
        id: 10,
        fullName: { name: 'Léonie', surname: 'Simonou', lastName: 'Pendrill' },
        birthDate: '8/1/1942',
        deathDate: '5/5/1988',
        sex: 'Male',
        group: 'Blue',
    },
    {
        id: 11,
        fullName: { name: 'Mahélie', surname: 'Bastone', lastName: 'Hamner' },
        birthDate: '4/12/1914',
        deathDate: '7/24/1907',
        sex: 'Female',
        group: 'Turquoise',
    },
    {
        id: 12,
        fullName: { name: 'Géraldine', surname: 'Lippatt', lastName: 'Cabane' },
        birthDate: '7/13/1905',
        deathDate: '12/7/1978',
        sex: 'Female',
        group: 'Pink',
    },
    {
        id: 13,
        fullName: {
            name: 'Marie-hélène',
            surname: 'Bellis',
            lastName: 'Dashper',
        },
        birthDate: '1/26/1902',
        deathDate: '11/4/1954',
        sex: 'Female',
        group: 'Yellow',
    },
    {
        id: 14,
        fullName: {
            name: 'Médiamass',
            surname: 'Bosson',
            lastName: 'Sotheron',
        },
        birthDate: '1/12/1969',
        deathDate: '4/22/1976',
        sex: 'Male',
        group: 'Goldenrod',
    },
    {
        id: 15,
        fullName: { name: 'Åsa', surname: 'Dugget', lastName: 'Skip' },
        birthDate: '1/23/1952',
        deathDate: '11/1/1931',
        sex: 'Female',
        group: 'Aquamarine',
    },
    {
        id: 16,
        fullName: { name: 'Sòng', surname: 'Kingswood', lastName: 'Buye' },
        birthDate: '12/22/1967',
        deathDate: '7/6/1964',
        sex: 'Female',
        group: 'Violet',
    },
    {
        id: 17,
        fullName: { name: 'Camélia', surname: 'Keizman', lastName: 'Samsin' },
        birthDate: '8/25/1951',
        deathDate: '2/24/1937',
        sex: 'Female',
        group: 'Aquamarine',
    },
    {
        id: 18,
        fullName: { name: 'Desirée', surname: 'Loude', lastName: 'MacVicar' },
        birthDate: '5/4/1955',
        deathDate: '3/1/1961',
        sex: 'Male',
        group: 'Red',
    },
    {
        id: 19,
        fullName: { name: 'Néhémie', surname: 'Guinery', lastName: 'Jacklin' },
        birthDate: '1/7/1961',
        deathDate: '12/13/1963',
        sex: 'Female',
        group: 'Mauv',
    },
    {
        id: 20,
        fullName: { name: 'Yè', surname: 'Derle', lastName: 'Samworth' },
        birthDate: '11/10/1952',
        deathDate: '12/13/1971',
        sex: 'Female',
        group: 'Blue',
    },
    {
        id: 21,
        fullName: { name: 'Mén', surname: 'Vasiltsov', lastName: 'Forshaw' },
        birthDate: '6/11/1968',
        deathDate: '8/12/1958',
        sex: 'Male',
        group: 'Puce',
    },
    {
        id: 22,
        fullName: {
            name: 'Bénédicte',
            surname: 'Seelbach',
            lastName: 'Vondrak',
        },
        birthDate: '12/31/1929',
        deathDate: '4/29/1970',
        sex: 'Male',
        group: 'Yellow',
    },
    {
        id: 23,
        fullName: { name: 'Aí', surname: 'Dana', lastName: 'Amerighi' },
        birthDate: '2/4/1901',
        deathDate: '7/6/1918',
        sex: 'Male',
        group: 'Teal',
    },
    {
        id: 24,
        fullName: { name: 'Ruò', surname: 'Tunder', lastName: 'Vayne' },
        birthDate: '6/5/1917',
        deathDate: '4/20/1983',
        sex: 'Male',
        group: 'Orange',
    },
    {
        id: 25,
        fullName: {
            name: 'Måns',
            surname: 'Southerden',
            lastName: 'Sheldrick',
        },
        birthDate: '1/8/1918',
        deathDate: '11/30/1914',
        sex: 'Male',
        group: 'Pink',
    },
    {
        id: 26,
        fullName: { name: 'Åslög', surname: 'Gilvear', lastName: 'Idale' },
        birthDate: '3/17/1902',
        deathDate: '10/8/1906',
        sex: 'Male',
        group: 'Crimson',
    },
    {
        id: 27,
        fullName: { name: 'Wá', surname: 'Nicholas', lastName: 'Brandham' },
        birthDate: '2/3/1970',
        deathDate: '4/9/1904',
        sex: 'Female',
        group: 'Red',
    },
    {
        id: 28,
        fullName: {
            name: 'Bérénice',
            surname: 'Dimberline',
            lastName: 'Bowdidge',
        },
        birthDate: '11/17/1940',
        deathDate: '3/18/1901',
        sex: 'Male',
        group: 'Mauv',
    },
    {
        id: 29,
        fullName: { name: 'Estée', surname: 'Heffernon', lastName: 'Pie' },
        birthDate: '6/26/1942',
        deathDate: '4/1/1965',
        sex: 'Genderfluid',
        group: 'Blue',
    },
    {
        id: 30,
        fullName: { name: 'Vénus', surname: 'Fleetham', lastName: 'Oxtarby' },
        birthDate: '9/23/1906',
        deathDate: '11/26/1962',
        sex: 'Male',
        group: 'Mauv',
    },
    {
        id: 31,
        fullName: { name: 'Magdalène', surname: 'Mark', lastName: 'Hanalan' },
        birthDate: '11/12/1962',
        deathDate: '9/10/1933',
        sex: 'Genderfluid',
        group: 'Blue',
    },
    {
        id: 32,
        fullName: { name: 'Thérèsa', surname: 'Bispham', lastName: 'Edeson' },
        birthDate: '3/17/1909',
        deathDate: '10/8/1956',
        sex: 'Female',
        group: 'Pink',
    },
    {
        id: 33,
        fullName: { name: 'Léonore', surname: 'Prator', lastName: 'Hyndson' },
        birthDate: '9/14/1919',
        deathDate: '4/12/1982',
        sex: 'Female',
        group: 'Fuscia',
    },
    {
        id: 34,
        fullName: {
            name: 'Noëlla',
            surname: 'Lillistone',
            lastName: 'Bartels-Ellis',
        },
        birthDate: '3/3/1933',
        deathDate: '5/21/1974',
        sex: 'Female',
        group: 'Green',
    },
    {
        id: 35,
        fullName: { name: 'Laurène', surname: 'Confort', lastName: 'Morhall' },
        birthDate: '3/1/1955',
        deathDate: '2/2/1933',
        sex: 'Agender',
        group: 'Orange',
    },
    {
        id: 36,
        fullName: { name: 'Réjane', surname: 'Rippin', lastName: 'Moscon' },
        birthDate: '5/25/1906',
        deathDate: '2/6/1963',
        sex: 'Female',
        group: 'Red',
    },
    {
        id: 37,
        fullName: { name: 'Aurélie', surname: 'McRorie', lastName: 'Elwin' },
        birthDate: '11/11/1904',
        deathDate: '8/8/1902',
        sex: 'Polygender',
        group: 'Pink',
    },
    {
        id: 38,
        fullName: { name: 'Maëline', surname: 'Dreier', lastName: 'Medcalfe' },
        birthDate: '12/14/1958',
        deathDate: '11/5/1955',
        sex: 'Female',
        group: 'Fuscia',
    },
    {
        id: 39,
        fullName: {
            name: 'Stéphanie',
            surname: 'Philipeaux',
            lastName: 'Crowne',
        },
        birthDate: '8/2/1925',
        deathDate: '2/26/1969',
        sex: 'Male',
        group: 'Red',
    },
    {
        id: 40,
        fullName: { name: 'Séréna', surname: 'Maciak', lastName: 'Lifsey' },
        birthDate: '10/6/1929',
        deathDate: '9/3/1932',
        sex: 'Female',
        group: 'Green',
    },
    {
        id: 41,
        fullName: { name: 'Angèle', surname: 'Fussey', lastName: 'Leyburn' },
        birthDate: '6/13/1958',
        deathDate: '7/29/1967',
        sex: 'Female',
        group: 'Khaki',
    },
    {
        id: 42,
        fullName: { name: 'Yáo', surname: 'Henker', lastName: 'Kindley' },
        birthDate: '6/30/1932',
        deathDate: '10/21/1931',
        sex: 'Female',
        group: 'Turquoise',
    },
    {
        id: 43,
        fullName: { name: 'Daphnée', surname: 'Pieter', lastName: 'Thurbon' },
        birthDate: '12/12/1958',
        deathDate: '6/14/1953',
        sex: 'Male',
        group: 'Goldenrod',
    },
    {
        id: 44,
        fullName: { name: 'Méng', surname: 'Bytheway', lastName: 'Stibbs' },
        birthDate: '6/15/1938',
        deathDate: '9/23/1906',
        sex: 'Female',
        group: 'Teal',
    },
    {
        id: 45,
        fullName: {
            name: 'Simplifiés',
            surname: 'McConville',
            lastName: 'Liddell',
        },
        birthDate: '4/3/1934',
        deathDate: '7/24/1955',
        sex: 'Male',
        group: 'Crimson',
    },
    {
        id: 46,
        fullName: {
            name: 'Adélaïde',
            surname: 'Grinsdale',
            lastName: 'Hatterslay',
        },
        birthDate: '5/18/1926',
        deathDate: '7/17/1900',
        sex: 'Male',
        group: 'Indigo',
    },
    {
        id: 47,
        fullName: {
            name: 'Laurène',
            surname: 'Ricciardello',
            lastName: 'Schreurs',
        },
        birthDate: '11/10/1946',
        deathDate: '7/12/1948',
        sex: 'Female',
        group: 'Aquamarine',
    },
    {
        id: 48,
        fullName: { name: 'Yóu', surname: 'Risley', lastName: 'Van den Oord' },
        birthDate: '8/11/1938',
        deathDate: '11/25/1956',
        sex: 'Male',
        group: 'Red',
    },
    {
        id: 49,
        fullName: {
            name: 'Médiamass',
            surname: 'Yukhtin',
            lastName: 'Chellenham',
        },
        birthDate: '3/4/1930',
        deathDate: '6/16/1958',
        sex: 'Male',
        group: 'Crimson',
    },
    {
        id: 50,
        fullName: { name: 'Maëlann', surname: 'Tite', lastName: 'Heers' },
        birthDate: '4/9/1951',
        deathDate: '11/1/1968',
        sex: 'Female',
        group: 'Indigo',
    },
    {
        id: 51,
        fullName: { name: 'Ruò', surname: 'Swanborrow', lastName: 'Petty' },
        birthDate: '10/27/1927',
        deathDate: '4/15/1903',
        sex: 'Male',
        group: 'Teal',
    },
    {
        id: 52,
        fullName: { name: 'Clémence', surname: 'Chicken', lastName: 'Goricke' },
        birthDate: '8/16/1964',
        deathDate: '6/23/1936',
        sex: 'Male',
        group: 'Yellow',
    },
    {
        id: 53,
        fullName: { name: 'Cinéma', surname: 'Espadero', lastName: 'Dyter' },
        birthDate: '11/9/1938',
        deathDate: '5/7/1903',
        sex: 'Male',
        group: 'Red',
    },
    {
        id: 54,
        fullName: { name: 'Mélia', surname: 'Menhci', lastName: 'Lethardy' },
        birthDate: '11/21/1911',
        deathDate: '3/14/1983',
        sex: 'Female',
        group: 'Khaki',
    },
    {
        id: 55,
        fullName: { name: 'Gisèle', surname: 'Lafond', lastName: 'Milnes' },
        birthDate: '9/25/1901',
        deathDate: '3/15/1910',
        sex: 'Female',
        group: 'Puce',
    },
    {
        id: 56,
        fullName: {
            name: 'Marylène',
            surname: 'Manger',
            lastName: 'Whitbread',
        },
        birthDate: '1/1/1948',
        deathDate: '4/6/1986',
        sex: 'Female',
        group: 'Purple',
    },
    {
        id: 57,
        fullName: {
            name: 'Bérénice',
            surname: 'Berecloth',
            lastName: 'Verrell',
        },
        birthDate: '7/28/1961',
        deathDate: '8/15/1920',
        sex: 'Female',
        group: 'Violet',
    },
    {
        id: 58,
        fullName: { name: 'Laïla', surname: 'Diboll', lastName: 'McTiernan' },
        birthDate: '3/21/1945',
        deathDate: '4/15/1945',
        sex: 'Male',
        group: 'Violet',
    },
    {
        id: 59,
        fullName: {
            name: 'Publicité',
            surname: 'Eshmade',
            lastName: 'Ciccerale',
        },
        birthDate: '5/3/1901',
        deathDate: '3/22/1988',
        sex: 'Male',
        group: 'Violet',
    },
    {
        id: 60,
        fullName: { name: 'Estève', surname: 'Goricke', lastName: 'Levee' },
        birthDate: '7/1/1904',
        deathDate: '2/21/1901',
        sex: 'Male',
        group: 'Maroon',
    },
    {
        id: 61,
        fullName: { name: 'Yáo', surname: 'Rewan', lastName: 'Dripps' },
        birthDate: '12/28/1950',
        deathDate: '1/30/1955',
        sex: 'Female',
        group: 'Orange',
    },
    {
        id: 62,
        fullName: { name: 'Lyséa', surname: 'Hoodless', lastName: 'Duncanson' },
        birthDate: '10/23/1906',
        deathDate: '6/6/1928',
        sex: 'Female',
        group: 'Maroon',
    },
    {
        id: 63,
        fullName: { name: 'Åsa', surname: 'St. Leger', lastName: 'Bewley' },
        birthDate: '4/8/1934',
        deathDate: '8/31/1960',
        sex: 'Male',
        group: 'Yellow',
    },
    {
        id: 64,
        fullName: { name: 'Léane', surname: 'Snepp', lastName: 'Kingswood' },
        birthDate: '5/7/1932',
        deathDate: '9/6/1932',
        sex: 'Female',
        group: 'Green',
    },
    {
        id: 65,
        fullName: { name: 'Clémence', surname: 'Hauger', lastName: 'Trippack' },
        birthDate: '12/30/1929',
        deathDate: '6/7/1907',
        sex: 'Male',
        group: 'Indigo',
    },
    {
        id: 66,
        fullName: { name: 'Gérald', surname: 'Swadlin', lastName: 'Lesser' },
        birthDate: '7/4/1928',
        deathDate: '8/2/1909',
        sex: 'Male',
        group: 'Blue',
    },
    {
        id: 67,
        fullName: { name: 'Eugénie', surname: 'Hakeworth', lastName: 'Bendig' },
        birthDate: '4/17/1904',
        deathDate: '7/20/1955',
        sex: 'Female',
        group: 'Red',
    },
    {
        id: 68,
        fullName: { name: 'Michèle', surname: 'Gascoyen', lastName: 'Bayly' },
        birthDate: '4/18/1912',
        deathDate: '11/14/1986',
        sex: 'Female',
        group: 'Blue',
    },
    {
        id: 69,
        fullName: { name: 'Adélaïde', surname: 'Durrans', lastName: 'Veque' },
        birthDate: '11/14/1968',
        deathDate: '1/4/1934',
        sex: 'Male',
        group: 'Purple',
    },
    {
        id: 70,
        fullName: { name: 'Méghane', surname: 'Zoephel', lastName: 'Killoran' },
        birthDate: '8/4/1927',
        deathDate: '4/16/1903',
        sex: 'Male',
        group: 'Maroon',
    },
    {
        id: 71,
        fullName: { name: 'Estève', surname: 'Fluit', lastName: 'Gair' },
        birthDate: '4/6/1914',
        deathDate: '2/28/1901',
        sex: 'Male',
        group: 'Aquamarine',
    },
    {
        id: 72,
        fullName: {
            name: 'Marie-noël',
            surname: 'Caser',
            lastName: 'Cutbirth',
        },
        birthDate: '5/13/1966',
        deathDate: '5/30/1954',
        sex: 'Male',
        group: 'Red',
    },
    {
        id: 73,
        fullName: {
            name: 'Bérengère',
            surname: 'Skoggings',
            lastName: 'Bosley',
        },
        birthDate: '10/1/1914',
        deathDate: '11/26/1977',
        sex: 'Female',
        group: 'Fuscia',
    },
    {
        id: 74,
        fullName: { name: 'Zhì', surname: 'Archley', lastName: 'Itshak' },
        birthDate: '1/29/1920',
        deathDate: '5/25/1957',
        sex: 'Male',
        group: 'Crimson',
    },
    {
        id: 75,
        fullName: {
            name: 'Séréna',
            surname: 'Dyos',
            lastName: 'Franceschielli',
        },
        birthDate: '1/14/1922',
        deathDate: '2/12/1915',
        sex: 'Male',
        group: 'Fuscia',
    },
    {
        id: 76,
        fullName: { name: 'Erwéi', surname: 'Yeaman', lastName: 'Willgress' },
        birthDate: '12/4/1963',
        deathDate: '5/19/1904',
        sex: 'Non-binary',
        group: 'Orange',
    },
    {
        id: 77,
        fullName: { name: 'Maéna', surname: 'Juliff', lastName: 'Faldo' },
        birthDate: '3/30/1908',
        deathDate: '10/31/1942',
        sex: 'Female',
        group: 'Purple',
    },
    {
        id: 78,
        fullName: { name: 'Aí', surname: 'Ovesen', lastName: 'McWilliams' },
        birthDate: '9/5/1936',
        deathDate: '3/31/1974',
        sex: 'Male',
        group: 'Fuscia',
    },
    {
        id: 79,
        fullName: { name: 'Garçon', surname: 'Tofano', lastName: 'Vose' },
        birthDate: '8/31/1901',
        deathDate: '11/15/1901',
        sex: 'Female',
        group: 'Teal',
    },
    {
        id: 80,
        fullName: { name: 'Maïlis', surname: 'Domniney', lastName: 'Bebis' },
        birthDate: '7/4/1922',
        deathDate: '3/2/1986',
        sex: 'Male',
        group: 'Purple',
    },
    {
        id: 81,
        fullName: { name: 'Mélia', surname: 'Ridde', lastName: 'Issac' },
        birthDate: '4/11/1941',
        deathDate: '10/12/1909',
        sex: 'Genderfluid',
        group: 'Teal',
    },
    {
        id: 82,
        fullName: {
            name: 'Mélia',
            surname: 'Bowmaker',
            lastName: 'Korneichik',
        },
        birthDate: '2/4/1942',
        deathDate: '10/13/1907',
        sex: 'Female',
        group: 'Purple',
    },
    {
        id: 83,
        fullName: { name: 'Séverine', surname: 'Miroy', lastName: 'Fulk' },
        birthDate: '11/21/1929',
        deathDate: '2/18/1965',
        sex: 'Female',
        group: 'Turquoise',
    },
    {
        id: 84,
        fullName: { name: 'Céline', surname: 'Bruckent', lastName: 'Whodcoat' },
        birthDate: '7/31/1935',
        deathDate: '2/10/1959',
        sex: 'Male',
        group: 'Turquoise',
    },
    {
        id: 85,
        fullName: { name: 'Marlène', surname: 'Lazar', lastName: 'Kemery' },
        birthDate: '8/31/1903',
        deathDate: '10/19/1947',
        sex: 'Agender',
        group: 'Yellow',
    },
    {
        id: 86,
        fullName: { name: 'Maéna', surname: 'Kirk', lastName: 'Pellman' },
        birthDate: '6/12/1922',
        deathDate: '2/6/1919',
        sex: 'Female',
        group: 'Indigo',
    },
    {
        id: 87,
        fullName: { name: 'Börje', surname: 'Fadden', lastName: 'Sopper' },
        birthDate: '6/21/1911',
        deathDate: '12/11/1989',
        sex: 'Polygender',
        group: 'Green',
    },
    {
        id: 88,
        fullName: { name: 'Hélèna', surname: 'Krates', lastName: 'Cicchillo' },
        birthDate: '2/9/1937',
        deathDate: '6/27/1907',
        sex: 'Male',
        group: 'Purple',
    },
    {
        id: 89,
        fullName: { name: 'Lóng', surname: 'Napoleone', lastName: 'Chree' },
        birthDate: '4/29/1916',
        deathDate: '11/7/1936',
        sex: 'Female',
        group: 'Goldenrod',
    },
    {
        id: 90,
        fullName: { name: 'Lyséa', surname: 'Bowlas', lastName: 'Venny' },
        birthDate: '10/24/1921',
        deathDate: '5/29/1927',
        sex: 'Male',
        group: 'Fuscia',
    },
    {
        id: 91,
        fullName: { name: 'Maïlis', surname: 'Egdal', lastName: 'Dunnet' },
        birthDate: '5/13/1930',
        deathDate: '2/16/1917',
        sex: 'Male',
        group: 'Khaki',
    },
    {
        id: 92,
        fullName: { name: 'Bénédicte', surname: 'Arents', lastName: 'Askham' },
        birthDate: '8/7/1914',
        deathDate: '3/15/1913',
        sex: 'Female',
        group: 'Maroon',
    },
    {
        id: 93,
        fullName: { name: 'Desirée', surname: 'Benz', lastName: 'Forder' },
        birthDate: '8/27/1916',
        deathDate: '10/16/1989',
        sex: 'Male',
        group: 'Pink',
    },
    {
        id: 94,
        fullName: {
            name: 'Aimée',
            surname: "O'Doogan",
            lastName: 'Tomaszynski',
        },
        birthDate: '4/23/1970',
        deathDate: '5/24/1921',
        sex: 'Female',
        group: 'Khaki',
    },
    {
        id: 95,
        fullName: {
            name: 'Réservés',
            surname: 'Cleyne',
            lastName: 'Trobridge',
        },
        birthDate: '2/13/1957',
        deathDate: '3/4/1985',
        sex: 'Female',
        group: 'Blue',
    },
    {
        id: 96,
        fullName: { name: 'Laurélie', surname: 'Dowrey', lastName: 'Treble' },
        birthDate: '2/11/1964',
        deathDate: '10/11/1945',
        sex: 'Female',
        group: 'Blue',
    },
    {
        id: 97,
        fullName: {
            name: 'Frédérique',
            surname: 'Monan',
            lastName: 'Ludgrove',
        },
        birthDate: '10/20/1945',
        deathDate: '6/6/1962',
        sex: 'Female',
        group: 'Crimson',
    },
    {
        id: 98,
        fullName: { name: 'Yáo', surname: 'Bygreaves', lastName: 'Bradfield' },
        birthDate: '3/27/1908',
        deathDate: '6/22/1954',
        sex: 'Female',
        group: 'Violet',
    },
    {
        id: 99,
        fullName: { name: 'Loïca', surname: 'Pritchard', lastName: 'Tytler' },
        birthDate: '6/20/1901',
        deathDate: '4/24/1927',
        sex: 'Male',
        group: 'Fuscia',
    },
    {
        id: 100,
        fullName: { name: 'Eliès', surname: 'Zielinski', lastName: 'Danahar' },
        birthDate: '2/1/1912',
        deathDate: '5/22/1964',
        sex: 'Non-binary',
        group: 'Violet',
    },
]

const links = [
    {
        source: 1,
        target: 2,
    },
    {
        source: 1,
        target: 3,
    },
    {
        source: 1,
        target: 4,
    },
    {
        source: 1,
        target: 5,
    },
    {
        source: 1,
        target: 6,
    },
    {
        source: 1,
        target: 7,
    },
    {
        source: 1,
        target: 8,
    },
    {
        source: 1,
        target: 9,
    },
    {
        source: 1,
        target: 10,
    },
    {
        source: 1,
        target: 11,
    },
    {
        source: 3,
        target: 12,
    },
    {
        source: 3,
        target: 13,
    },
    {
        source: 3,
        target: 14,
    },
    {
        source: 3,
        target: 15,
    },
    {
        source: 3,
        target: 16,
    },
    {
        source: 3,
        target: 17,
    },
    {
        source: 3,
        target: 18,
    },
    {
        source: 3,
        target: 19,
    },
    {
        source: 3,
        target: 20,
    },
    {
        source: 4,
        target: 21,
    },
    {
        source: 4,
        target: 22,
    },
    {
        source: 4,
        target: 23,
    },
    {
        source: 4,
        target: 24,
    },
    {
        source: 4,
        target: 25,
    },
    {
        source: 4,
        target: 26,
    },
    {
        source: 5,
        target: 27,
    },
    {
        source: 5,
        target: 28,
    },
    {
        source: 5,
        target: 29,
    },
    {
        source: 5,
        target: 30,
    },
    {
        source: 5,
        target: 31,
    },
    {
        source: 5,
        target: 32,
    },
    {
        source: 5,
        target: 33,
    },
    {
        source: 5,
        target: 34,
    },
    {
        source: 5,
        target: 35,
    },
    {
        source: 5,
        target: 36,
    },
    {
        source: 5,
        target: 37,
    },
    {
        source: 5,
        target: 38,
    },
    {
        source: 5,
        target: 39,
    },
    {
        source: 5,
        target: 40,
    },
    {
        source: 6,
        target: 1,
    },
    {
        source: 6,
        target: 2,
    },
    {
        source: 6,
        target: 3,
    },
    {
        source: 6,
        target: 32,
    },
    {
        source: 6,
        target: 65,
    },
    {
        source: 6,
        target: 76,
    },
    {
        source: 6,
        target: 87,
    },
    {
        source: 6,
        target: 98,
    },
    {
        source: 6,
        target: 99,
    },
    {
        source: 6,
        target: 100,
    },
    {
        source: 10,
        target: 6,
    },
    {
        source: 10,
        target: 7,
    },
    {
        source: 10,
        target: 8,
    },
    {
        source: 10,
        target: 9,
    },
    {
        source: 10,
        target: 11,
    },
    {
        source: 10,
        target: 12,
    },
    {
        source: 10,
        target: 13,
    },
    {
        source: 10,
        target: 14,
    },
    {
        source: 10,
        target: 15,
    },
    {
        source: 10,
        target: 16,
    },
    {
        source: 10,
        target: 17,
    },
    {
        source: 10,
        target: 18,
    },
    {
        source: 10,
        target: 19,
    },
    {
        source: 10,
        target: 20,
    },
    {
        source: 56,
        target: 6,
    },
    {
        source: 56,
        target: 7,
    },
    {
        source: 56,
        target: 8,
    },
    {
        source: 56,
        target: 9,
    },
    {
        source: 44,
        target: 10,
    },
    {
        source: 44,
        target: 11,
    },
    {
        source: 44,
        target: 12,
    },
    {
        source: 44,
        target: 77,
    },
    {
        source: 44,
        target: 33,
    },
    {
        source: 44,
        target: 45,
    },
    {
        source: 44,
        target: 46,
    },
    {
        source: 44,
        target: 47,
    },
    {
        source: 44,
        target: 48,
    },
    {
        source: 44,
        target: 49,
    },
    {
        source: 44,
        target: 33,
    },
    {
        source: 44,
        target: 50,
    },
    {
        source: 44,
        target: 51,
    },
    {
        source: 44,
        target: 52,
    },
    {
        source: 44,
        target: 53,
    },
    {
        source: 44,
        target: 54,
    },
]

export const responseGraph = {
    persons: getGraphResponse,
    links: links,
}
